"use client";
import { Canvas, useFrame } from "@react-three/fiber";
import { Environment, RoundedBox, Text } from "@react-three/drei";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";

const content=[
{title:"CAPTAIN B",sub:"IDENTITY · STORY · MISSION",body:"A knowledge-sharing personal brand built around ideas, technology, creativity and practical learning.",slug:"about",position:[-2.45,1.55,-5] as [number,number,number]},
{title:"AI & TECHNOLOGY",sub:"01 · FUTURE SYSTEMS",body:"AI tools, emerging technology, experiments and practical workflows.",slug:"ai",position:[2.45,1.55,-1.7] as [number,number,number]},
{title:"BUSINESS",sub:"02 · BRAND · STRATEGY",body:"Branding, marketing, positioning, growth and digital experiences.",slug:"business",position:[-2.45,1.55,1.8] as [number,number,number]},
{title:"KNOWLEDGE LOG",sub:"03 · INSIGHTS · LESSONS",body:"Ideas, observations, experiments, cases and lessons worth sharing.",slug:"knowledge",position:[2.45,1.55,5.3] as [number,number,number]},
{title:"RESOURCES",sub:"04 · TOOLS · REFERENCES",body:"Useful tools, templates, references and systems for learning and creating.",slug:"resources",position:[-2.45,1.55,8.8] as [number,number,number]},
{title:"CONNECT",sub:"05 · OPEN CHANNEL",body:"Collaborate, start a conversation or follow the next flight.",slug:"connect",position:[2.45,1.55,12.3] as [number,number,number]}
] as const;

function HoloRing({radius=2.55}:{radius?:number}){const ref=useRef<THREE.Group>(null);useFrame((_,d)=>{if(ref.current)ref.current.rotation.z+=d*.06});return <group ref={ref}>{[0,1].map(i=><mesh key={i} rotation={[0,0,i*Math.PI/2]}><torusGeometry args={[radius+i*.18,.009,8,96]}/><meshStandardMaterial color="#67e8f9" emissive="#06b6d4" emissiveIntensity={2} transparent opacity={.2}/></mesh>)}</group>}

function HologramCard({item}:{item:typeof content[number]}){const ref=useRef<THREE.Group>(null);const[hover,setHover]=useState(false);useFrame(({clock})=>{if(!ref.current)return;ref.current.position.y=item.position[1]+Math.sin(clock.elapsedTime*.55+item.position[2])*.045;ref.current.rotation.y=Math.sin(clock.elapsedTime*.35+item.position[2])*.012;const s=hover?1.055:1;ref.current.scale.lerp(new THREE.Vector3(s,s,s),.12)});return <group ref={ref} position={item.position} onClick={()=>window.location.href=`/explore/${item.slug}`} onPointerOver={e=>{e.stopPropagation();setHover(true);document.body.style.cursor="pointer"}} onPointerOut={()=>{setHover(false);document.body.style.cursor="default"}}><RoundedBox args={[3.25,1.65,.045]} radius={.16} smoothness={8}><meshStandardMaterial color={hover?"#092b40":"#02101b"} emissive="#0369a1" emissiveIntensity={hover?.9:.35} transparent opacity={hover?.88:.72} metalness={.65} roughness={.05}/></RoundedBox><mesh position={[0,.8,.04]}><boxGeometry args={[2.6,.012,.015]}/><meshStandardMaterial color={hover?"#ffffff":"#67e8f9"} emissive="#22d3ee" emissiveIntensity={hover?5:2.5}/></mesh><Text position={[-1.25,.47,.055]} fontSize={.09} color={hover?"#ffffff":"#67e8f9"} anchorX="left">{item.sub}</Text><Text position={[-1.25,.2,.055]} fontSize={.17} color={hover?"#ffffff":"#eafcff"} anchorX="left" maxWidth={2.55}>{item.title}</Text><Text position={[-1.25,-.22,.055]} fontSize={.065} color={hover?"#e8fbff":"#b9dce7"} anchorX="left" maxWidth={2.55}>{item.body}</Text><Text position={[-1.25,-.59,.055]} fontSize={.055} color={hover?"#ffffff":"#67e8f9"} anchorX="left">{hover?"CLICK TO ENTER ↗":"OPEN MODULE ↗"}</Text></group>}

function AircraftShell(){return <group><mesh position={[0,3.8,2]}><cylinderGeometry args={[4.75,4.75,31,64,1,true,Math.PI/2,Math.PI]}/><meshStandardMaterial color="#04070c" metalness={.95} roughness={.14} side={THREE.DoubleSide}/></mesh><mesh position={[0,-2.25,2]}><boxGeometry args={[8,.18,31]}/><meshStandardMaterial color="#05090f" metalness={.85} roughness={.18}/></mesh><RoundedBox position={[0,3.35,2]} args={[7.4,.32,31]} radius={.12}><meshStandardMaterial color="#090d14" metalness={.85} roughness={.16}/></RoundedBox></group>}
function Windows(){return <group>{[-8.5,-5.2,-1.9,1.4,4.7,8,11.3,14.6].map(z=><group key={z} position={[0,.7,z]}>{[-3.76,3.76].map(x=><RoundedBox key={x} position={[x,0,0]} args={[.2,2.5,1.8]} radius={.2}><meshStandardMaterial color="#05090f" metalness={.86} roughness={.1}/></RoundedBox>)}</group>)}</group>}
function HeroFront(){return <group position={[0,1.5,-14]}><mesh rotation={[Math.PI/2,0,0]}><sphereGeometry args={[5.3,64,32,0,Math.PI*2,0,Math.PI*.55]}/><meshStandardMaterial color="#080f17" metalness={.97} roughness={.09}/></mesh><RoundedBox position={[0,1,.22]} args={[8.1,4,.14]} radius={.5}><meshStandardMaterial color="#01070d" metalness={.96} roughness={.07}/></RoundedBox><RoundedBox position={[0,1,.31]} args={[7.45,3.45,.05]} radius={.42}><meshStandardMaterial color="#05263e" emissive="#075985" emissiveIntensity={.35} transparent opacity={.9}/></RoundedBox>{[-2.5,2.5].map(x=><group key={x} position={[x,-2.1,.2]}><mesh rotation={[0,Math.PI/2,0]}><cylinderGeometry args={[.7,.95,2.8,32]}/><meshStandardMaterial color="#111a22" metalness={.97} roughness={.1}/></mesh><mesh rotation={[0,Math.PI/2,0]}><torusGeometry args={[.52,.09,18,40]}/><meshStandardMaterial color="#22d3ee" emissive="#22d3ee" emissiveIntensity={2.4}/></mesh></group>)}</group>}
function Cockpit(){return <group position={[0,0,-9.2]}><RoundedBox position={[0,2.25,-.9]} args={[9.2,5.2,.28]} radius={.48}><meshStandardMaterial color="#010408" metalness={.96} roughness={.1}/></RoundedBox><RoundedBox position={[0,2.25,-.7]} args={[8.5,4.55,.07]} radius={.38}><meshStandardMaterial color="#031b2d" emissive="#075985" emissiveIntensity={.25} transparent opacity={.94}/></RoundedBox>{[-3.15,-1.05,1.05,3.15].map(x=><RoundedBox key={x} position={[x,2.1,-.58]} args={[1.7,1.38,.08]} radius={.14}><meshStandardMaterial color="#020910" emissive="#0369a1" emissiveIntensity={.28}/></RoundedBox>)}<RoundedBox position={[0,.05,-.2]} args={[8.9,1.55,1.55]} radius={.3}><meshStandardMaterial color="#090f17" metalness={.9} roughness={.12}/></RoundedBox></group>}
function LuxurySeat({x,z,pilot=false}:{x:number;z:number;pilot?:boolean}){return <group position={[x,-1.25,z]}><RoundedBox args={[1.55,.48,1.7]} radius={.22}><meshStandardMaterial color="#151c25" roughness={.15} metalness={.5}/></RoundedBox><RoundedBox position={[0,.9,.38]} args={[1.55,1.72,.5]} radius={.24}><meshStandardMaterial color="#0b121b" roughness={.14} metalness={.58}/></RoundedBox>{pilot&&<RoundedBox position={[0,1.48,.15]} args={[1.32,.16,.48]} radius={.06}><meshStandardMaterial color="#050a10" metalness={.82} roughness={.12}/></RoundedBox>}</group>}
function Pilot({x}:{x:number}){return <group position={[x,0,-7.75]}><LuxurySeat x={0} z={0} pilot/><mesh position={[0,1.95,0]}><sphereGeometry args={[.52,28,18]}/><meshStandardMaterial color="#9c684b" roughness={.5}/></mesh></group>}
function CameraMotion(){const[scroll,setScroll]=useState(0);useEffect(()=>{const h=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;setScroll(max>0?window.scrollY/max:0)};h();window.addEventListener("scroll",h,{passive:true});return()=>window.removeEventListener("scroll",h)},[]);useFrame(state=>{const p=THREE.MathUtils.smootherstep(scroll,0,1);state.camera.position.lerp(new THREE.Vector3(Math.sin(p*Math.PI*5)*.2,THREE.MathUtils.lerp(.3,.85,p),THREE.MathUtils.lerp(7.7,13.2,p)),.075);state.camera.lookAt(0,1,THREE.MathUtils.lerp(-8.8,12.2,p))});return null}
export default function AircraftScene(){return <div className="fixed inset-0 z-0 h-screen w-full"><Canvas camera={{position:[0,.3,7.7],fov:56}} dpr={[1,1.5]}><color attach="background" args={["#010409"]}/><fog attach="fog" args={["#020812",8,42]}/><ambientLight intensity={.34}/><directionalLight position={[0,9,-9]} intensity={1.9} color="#dff7ff"/><pointLight position={[0,1,-8]} intensity={8} distance={22} color="#0ea5e9"/><pointLight position={[0,2.5,4]} intensity={2.8} distance={18} color="#22d3ee"/><Environment preset="night"/><AircraftShell/><Windows/><HeroFront/><Cockpit/><Pilot x={-2.05}/><Pilot x={2.05}/>{[-1.85,1.85].map(x=><LuxurySeat key={`a-${x}`} x={x} z={-2.2}/>)}{[-1.85,1.85].map(x=><LuxurySeat key={`b-${x}`} x={x} z={2.2}/>)}{[-1.85,1.85].map(x=><LuxurySeat key={`c-${x}`} x={x} z={6.6}/>)}<HoloRing/>{content.map(item=><HologramCard key={item.title} item={item}/>)}<CameraMotion/></Canvas></div>}
