"use client";
import { Canvas, useFrame } from "@react-three/fiber";
import { Environment, RoundedBox } from "@react-three/drei";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";

function AircraftShell(){return <group><mesh position={[0,3.8,2]}><cylinderGeometry args={[4.75,4.75,31,64,1,true,Math.PI/2,Math.PI]}/><meshStandardMaterial color="#04070c" metalness={.95} roughness={.14} side={THREE.DoubleSide}/></mesh><mesh position={[0,-2.25,2]}><boxGeometry args={[8,.18,31]}/><meshStandardMaterial color="#05090f" metalness={.85} roughness={.18}/></mesh><RoundedBox position={[0,3.35,2]} args={[7.4,.32,31]} radius={.12}><meshStandardMaterial color="#090d14" metalness={.85} roughness={.16}/></RoundedBox></group>}
function Windows(){return <group>{[-8.5,-5.2,-1.9,1.4,4.7,8,11.3,14.6].map(z=><group key={z} position={[0,.7,z]}>{[-3.76,3.76].map(x=><RoundedBox key={x} position={[x,0,0]} args={[.2,2.5,1.8]} radius={.2}><meshStandardMaterial color="#05090f" metalness={.86} roughness={.1}/></RoundedBox>)}</group>)}</group>}
function HeroFront(){return <group position={[0,1.5,-14]}><mesh rotation={[Math.PI/2,0,0]}><sphereGeometry args={[5.3,64,32,0,Math.PI*2,0,Math.PI*.55]}/><meshStandardMaterial color="#080f17" metalness={.97} roughness={.09}/></mesh><RoundedBox position={[0,1,.22]} args={[8.1,4,.14]} radius={.5}><meshStandardMaterial color="#01070d" metalness={.96} roughness={.07}/></RoundedBox><RoundedBox position={[0,1,.31]} args={[7.45,3.45,.05]} radius={.42}><meshStandardMaterial color="#05263e" emissive="#075985" emissiveIntensity={.35} transparent opacity={.9}/></RoundedBox>{[-2.5,2.5].map(x=><group key={x} position={[x,-2.1,.2]}><mesh rotation={[0,Math.PI/2,0]}><cylinderGeometry args={[.7,.95,2.8,32]}/><meshStandardMaterial color="#111a22" metalness={.97} roughness={.1}/></mesh><mesh rotation={[0,Math.PI/2,0]}><torusGeometry args={[.52,.09,18,40]}/><meshStandardMaterial color="#22d3ee" emissive="#22d3ee" emissiveIntensity={2.4}/></mesh></group>)}</group>}
function Cockpit(){return <group position={[0,0,-9.2]}><RoundedBox position={[0,2.25,-.9]} args={[9.2,5.2,.28]} radius={.48}><meshStandardMaterial color="#010408" metalness={.96} roughness={.1}/></RoundedBox><RoundedBox position={[0,2.25,-.7]} args={[8.5,4.55,.07]} radius={.38}><meshStandardMaterial color="#031b2d" emissive="#075985" emissiveIntensity={.25} transparent opacity={.94}/></RoundedBox>{[-3.15,-1.05,1.05,3.15].map(x=><RoundedBox key={x} position={[x,2.1,-.58]} args={[1.7,1.38,.08]} radius={.14}><meshStandardMaterial color="#020910" emissive="#0369a1" emissiveIntensity={.28}/></RoundedBox>)}<RoundedBox position={[0,.05,-.2]} args={[8.9,1.55,1.55]} radius={.3}><meshStandardMaterial color="#090f17" metalness={.9} roughness={.12}/></RoundedBox></group>}
function LuxurySeat({x,z,pilot=false}:{x:number;z:number;pilot?:boolean}){return <group position={[x,-1.25,z]}><RoundedBox args={[1.55,.48,1.7]} radius={.22}><meshStandardMaterial color="#151c25" roughness={.15} metalness={.5}/></RoundedBox><RoundedBox position={[0,.9,.38]} args={[1.55,1.72,.5]} radius={.24}><meshStandardMaterial color="#0b121b" roughness={.14} metalness={.58}/></RoundedBox>{pilot&&<RoundedBox position={[0,1.48,.15]} args={[1.32,.16,.48]} radius={.06}><meshStandardMaterial color="#050a10" metalness={.82} roughness={.12}/></RoundedBox>}</group>}
function Pilot({x}:{x:number}){return <group position={[x,0,-7.75]}><LuxurySeat x={0} z={0} pilot/><mesh position={[0,1.95,0]}><sphereGeometry args={[.52,28,18]}/><meshStandardMaterial color="#9c684b" roughness={.5}/></mesh></group>}
function CameraMotion(){const[scroll,setScroll]=useState(0);useEffect(()=>{const h=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;setScroll(max>0?window.scrollY/max:0)};h();window.addEventListener("scroll",h,{passive:true});return()=>window.removeEventListener("scroll",h)},[]);useFrame(state=>{const p=THREE.MathUtils.smootherstep(scroll,0,1);state.camera.position.lerp(new THREE.Vector3(Math.sin(p*Math.PI*5)*.2,THREE.MathUtils.lerp(.3,.85,p),THREE.MathUtils.lerp(7.7,13.2,p)),.075);state.camera.lookAt(0,1,THREE.MathUtils.lerp(-8.8,12.2,p))});return null}
function View360({children}:{children:React.ReactNode}){const ref=useRef<THREE.Group>(null);const[target,setTarget]=useState(0);useEffect(()=>{const move=(e:PointerEvent)=>{const x=e.clientX/window.innerWidth;setTarget((x-.5)*Math.PI*2)};window.addEventListener("pointermove",move,{passive:true});return()=>window.removeEventListener("pointermove",move)},[]);useFrame(()=>{if(ref.current)ref.current.rotation.y=THREE.MathUtils.lerp(ref.current.rotation.y,target,.06)});return <group ref={ref}>{children}</group>}
export default function AircraftScene(){return <div className="fixed inset-0 z-0 h-screen w-full"><Canvas camera={{position:[0,.3,7.7],fov:56}} dpr={[1,1.5]}><color attach="background" args={["#010409"]}/><fog attach="fog" args={["#020812",8,42]}/><ambientLight intensity={.34}/><directionalLight position={[0,9,-9]} intensity={1.9} color="#dff7ff"/><pointLight position={[0,1,-8]} intensity={8} distance={22} color="#0ea5e9"/><pointLight position={[0,2.5,4]} intensity={2.8} distance={18} color="#22d3ee"/><Environment preset="night"/><View360><AircraftShell/><Windows/><HeroFront/><Cockpit/><Pilot x={-2.05}/><Pilot x={2.05}/>{[-1.85,1.85].map(x=><LuxurySeat key={`a-${x}`} x={x} z={-2.2}/>)}{[-1.85,1.85].map(x=><LuxurySeat key={`b-${x}`} x={x} z={2.2}/>)}{[-1.85,1.85].map(x=><LuxurySeat key={`c-${x}`} x={x} z={6.6}/>)}</View360><CameraMotion/></Canvas></div>}
